name: imess
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  firebase_storage: ^11.5.2
  google_sign_in: ^6.1.6
  image_picker: ^1.0.4
  get_storage: ^2.1.1
  intl: ^0.18.1
  photo_view: ^0.14.0
  country_code_picker: ^3.0.0
  url_launcher: ^6.2.1
  equatable: ^2.0.5
  get: 4.6.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
